#!/bin/bash

echo "Preparing user ${USER}"
echo "PATH=$PATH"

test -d ~/gpw-community-bsp/gpw-yocto-platform || /usr/local/bin/gpw_yocto_prepare
test -d ~/perl5/perlbrew/perls/perl-5.24.4 || /usr/local/bin/gpw_perl_prepare
